### ISSUE TITLE
sockgetm のゼロクリア時のバッファサイズが不正

### ISSUE THREAD

**Issue by vain0x** [onitama/OpenHSP#15]
memset の `sizeof(buf)` はここでは `sizeof(char*)` なので、おそらく間違っています。

https://github.com/onitama/OpenHSP/blob/01ef11a307896d1c2c3313c8af97287384a93ca4/src/hsp3/linux/hsp3gr_linux.cpp#L94-L100

**Comment by onitama** [comment]
https://github.com/onitama/OpenHSP/commit/31ef1ad04446407f8bf2d544cf031e8216059f35
ご指摘ありがとうございます。修正しました。
