### ISSUE TITLE
Raspberry Pi版HSP上でキーボードやマウスの検出に失敗する

### ISSUE THREAD

**Issue by mieki256** [onitama/OpenHSP#19]
### 概要

Raspberry Pi版HSP(hsp3dish)において、キーボードやマウス製品によっては、キー入力やマウス入力ができない状態になります。

### 動作確認環境

- Raspberry Pi Zero W
- Raspberry Pi OS buster

以下は問題が発生した製品ですが、どの製品も、Raspberry Pi OS buster のデスクトップ画面を操作する分には問題無く動作することを確認しています。HSP(hsp3dish)の実行時のみ、問題が発生します。

- Logicool K400r (USB接続ワイヤレスキーボード(タッチパッド付)) ... キー入力もマウス入力も無反応
- BUFFALO BSKBW03WH (USB接続ワイヤレスキーボード) ... キーボードとマウスの接続順によって、キー入力かマウス入力、どちらかしか受け付けなくなる
- A4Tech XL-755BK (USB有線接続マウス) ... キーボードとマウスの接続順によって、キー入力かマウス入力、どちらかしか受け付けなくなる。

尚、以下の製品はHSP(hsp3dish)でも動作しました。

- Lenovo KU-1255 (USB有線接続トラックポイント付キーボード) ... キーボードもトラックポイントも反応。
- Cherry G230 (G85-23100JAAESF) (USB有線接続キーボード)
- Logicool VX Nano (USB接続ワイヤレスマウス) ... ただし、BUFFALO BSKBW03WH と組み合わせた時は無反応。
- ELECOM M-BL21DBSV (USB接続ワイヤレスマウス) ... ただし、BUFFALO BSKBW03WH と組み合わせた時は無反応。

### 原因

OpenHSP/src/hsp3dish/raspbian/hsp3dish.cpp の initKeyboard()、updateKeyboard() 内で、/dev/input/by-id 以下に event-kbd(キーボード), event-mouse(マウス)が、それぞれ1つずつ出現することを前提にした実装のために問題が発生するようです。

問題が発生するキーボード・マウス製品について調べたところ、/dev/input/by-id に対して、以下の情報を返すことが分かりました。

- Logicool K400r ... event-mouse は返すが、event-kbd は返さない。また、kbd と mouse0 が同じevent番号に割り当てられる。
- BUFFALO BSKBW03WH ... event-kbd の他に event-mouse も返す。
- A4Tech XL-755BK ... event-mouse の他に event-kbd も返す。

結果、Logicool K400r 接続時は、HSPからはキーボードが存在しないものとして扱われてしまい、更に、updateKeyboard() の先頭で、キーボードが見つからないため、マウス入力の解析処理もキャンセルされ、キーボードもマウスも無反応の状態になります。

BUFFALO BSKBW03WH + A4Tech XL-755BK の接続時は、キーボードを1つ、マウスを1つ接続してある状態なのに、HSPからはキーボード2つ、マウス2つが接続されているように見えてしまい、キーボード側、もしくはマウス側の、片方の情報しか取得できない状態になります。

### 解決策の提案

手元の環境で hsp3dish.cpp の、initKeyboard()、updateKeyboard()、doneKeyboard() に修正を加えて試してみましたが、
以下の処理に変えることで問題が起きていた各製品も利用できるようになることを確認しました。

- /dev/input/by-id 以下に出現した event-kbd, event-mouse の数だけ、入力機器を監視する。(event-kbd x 2, event-mouse x 2 が出てきたら、計4つの event を監視対象にする。)
- マウスとキーボードに、別個のeventが割り当てられてる前提ではなく、1つの event の中にキー入力とマウス入力が混在していることを前提にして解析処理をする。

一応、手元で修正・動作確認したファイルも添付しておきます。

[hsp3dish.cpp.diff.txt](https://github.com/onitama/OpenHSP/files/6096272/hsp3dish.cpp.diff.txt)
[hsp3dish.cpp.txt](https://github.com/onitama/OpenHSP/files/6096273/hsp3dish.cpp.txt)

**Comment by onitama** [comment]
細かい検証と修正コードをありがとうございます。
HSP3.6β5で修正頂いたコードを反映させて頂きます。

**Comment by onitama** [comment]
masterにマージしました
