### ISSUE TITLE
ファイルの破損

### ISSUE THREAD

**Issue by Asugakoisi** [onitama/OpenHSP#22]
Dxライブラリとアイコンファイルが破損しています。

破損しているDxライブラリのあるディレクトリ
- [src/hsp3dish/win32/lib/lib](../tree/hsp36rc1/src/hsp3dish/win32/lib/lib)
- [src/hsp3dish/win32gp/lib/lib](../tree/hsp36rc1/src/hsp3dish/win32gp/lib/lib)

破損しているアイコンファイル
- [src/hsp3/win32gui/hsp3.ico](../tree/hsp36rc1/src/hsp3/win32gui/hsp3.ico)
- [src/hsp3dish/win32/hsp3.ico](../tree/hsp36rc1/src/hsp3dish/win32/hsp3.ico)
- [src/hsp3dish/win32gp/hsp3.ico](../tree/hsp36rc1/src/hsp3dish/win32gp/hsp3.ico)

**Comment by onitama** [comment]
ご指摘ありがとうございます。修正します。

**Comment by onitama** [comment]
hsp3.6rc1で反映しました
