### ISSUE TITLE
makefile.linuxのOBJSからlinux/hsp3ext_sock.oが抜けている

### ISSUE THREAD

**Issue by cielavenir** [onitama/OpenHSP#6]
linux/hsp3ext_sock.cppが最近追加されたようですが、対応する.oがOBJS内に追加されていないようです。

※OpenHSPはsvnとgitを併用して開発されているので、こういった報告をどこにすべきかよくわかっていません。報告する場所が別にあるのでしたら申し訳ありません。
※ svnが主なのであればPullRequestsを送るとsvn側がまずいかなと思ったので ~~そうしておりません。~~ PullRequestsを送るべきであればそのようにいたします。

**Comment by onitama** [comment]
ありがとうございます。
Linux/Raspbian版はgithubがメインになっているので、こちらにPRかMRを送って頂いて構いません。
本家のsvnに反映させる場合はこちらで行います。
